# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c56c4586df8d08ec97b501d4837a2c354c59af4b17c9e293b75aecbc40be26cf807a8ed4badd4776d95a7a85e246f6c925c34ef221e47a508479067b12a96da

test:
  secret_key_base: 37a1535d97be5dc6d8b85f681eb5fed95f69436a79f2293c7d99a8a0c3f0324b8b29cf7157dc9ccd52c53507c4e083b8a755de01a27b00c9d1e2c5313c70f5ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
